name: docker-publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to build (e.g., v4.9.99-graytip)'
        required: true
        default: 'v4.9.99-graytip'

env:
  NAPCAT_REPO: yukmakoto/NapCatQQ
  DOCKER_REPO: yukmakoto/napcat-docker

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get artifacts
        run: |
          bash get_artifacts.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.version }} ${{ env.NAPCAT_REPO }}
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run buildx and push
        run: |
          TAG=${{ github.event.inputs.version }}
          docker buildx build \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ env.DOCKER_REPO }}:$TAG \
            --tag ${{ env.DOCKER_REPO }}:latest \
            --file ./Dockerfile \
            .
      - name: Docker Hub logout
        if: always()
        run: docker logout
